# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: antbarbi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/20 20:14:59 by antbarbi          #+#    #+#              #
#    Updated: 2018/08/20 20:31:31 by antbarbi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_tail 
SRC =
FLAG = -Wall -Werror -Wextra
BIN = 

all :
	$(NAME)

$(NAME) :
	gcc

clean :
	rm -f

fclean : clean 
	rm -f

re : fclean all

